#!/bin/bash
mkdir -p "$1 at $(date)"/{about_me/{personal,professional},my_friends,my_system_info}
cd $1*
echo -e "https://www.facebook.com/$2" > about_me/personal/facebook.txt
echo -e "https://www.linkedin.com/in/$3" > about_me/professional/linkedin.txt
echo -e $(curl https://gist.githubusercontent.com/tegarimansyah/e91f335753ab2c7fb12815779677e914/raw/94864388379fecee450fde26e3e73bfb2bcda194/list%2520of%2520my%2520friends.txt) > my_friends/list_of_my_friends.txt
echo -e "My username: $USER\nWith host: $(uname -a)" > my_system_info/about_this_laptop.txt
echo -e "Connection to google:\n$(ping -c 3 forcesafesearch.google.com)" > my_system_info/internet_connection.txt
echo "ALTA Automate Script Challenge"
